name: Regenerate browser versions

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

env:
  package_dir: "/"

jobs:
  refresh-downstream-browsers-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install environment
        run: npm ci

      - name: Run generate-versions
        id: generate-versions-script
        run: |
          npm run generate-versions
          if [[ -n "$(git diff)" ]]; then
            echo "changes-available=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes-available=FALSE" >> $GITHUB_OUTPUT
          fi

      - name: Push changes to main
        if: steps.generate-versions-script.outputs.changes-available == 'TRUE'
        id: push-to-main
        run: |
          echo "changes have occurred, committing to main"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Updating static browser versions'
          git push origin main